# Generated by Django 4.2.3 on 2023-08-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_aimodel_textclassifier_textgen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='last_used_date',
            field=models.DateTimeField(),
        ),
    ]
