# Generated by Django 4.2.3 on 2023-08-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0004_alter_aimodel_last_used_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='last_used_date',
            field=models.DateTimeField(null=True),
        ),
    ]
